name: Tests
env:
  MIX_ENV: test
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on: push

jobs:
    test:
        runs-on: ubuntu-latest

        container:
            image: elixir:1.9.2-slim

        steps:
            -   uses: actions/checkout@v1
            -   name: Get deps cache
                uses: actions/cache@v1
                with:
                    path: deps/
                    key: ${{ runner.os }}-deps-${{ hashFiles('**/mix.lock') }}
                    restore-keys: ${{ runner.os }}-deps-
            -   name: Get build cache
                uses: actions/cache@v1
                with:
                    path: _build/test/
                    key: ${{ runner.os }}-build-${{ hashFiles('**/mix.lock') }}
                    restore-keys: ${{ runner.os }}-build-
            -   name: Install Dependencies
                run: |
                    mix local.rebar --force
                    mix local.hex --force
            -   name: Run Spotiauth Tests
                working-directory: ./spotiauth
                run: |
                    mix deps.get
                    mix coveralls.github
