name: Tests

on: push

jobs:
    test:
        runs-on: ubuntu-latest

        container:
            image: elixir:1.9.2-slim

        steps:
            -   uses: actions/checkout@v1
            -   name: Install Dependencies
                run: |
                    mix local.rebar --force
                    mix local.hex --force
            -   name: Run Spotiauth Tests
                working-directory: ./spotiauth
                run: |
                    mix deps.get
                    mix test
                env:
                    MIX_ENV: test
            -   name: Run Spotifyware Tests
                working-directory: ./spotifyware
                run: |
                    mix deps.get
                    mix test
                env:
                    MIX_ENV: test